.TH "/home/nightwalker/Class/C_Adv/biblio/inc/add_livre.h" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nightwalker/Class/C_Adv/biblio/inc/add_livre.h \- Les prototypes des fonctions qui gèrent l'ajout d'un nouveau Livre\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'sqlite3_client\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBadd_livre\fP (void)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Les prototypes des fonctions qui gèrent l'ajout d'un nouveau Livre\&. 


.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuteur\fP
.RS 4
\fCKOUASSI Yao Kan\fP 
.RE
.PP
\fBDate\fP
.RS 4
25 Avril 2021 
.RE
.PP

.PP
Définition dans le fichier \fBadd_livre\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void add_livre (void)"

.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void
.RE
.PP
Enregistre un nouveau Livre dans la base de donnees\&. Les informations du Livre sont demandees de façon interactive 
.PP
Définition à la ligne 15 du fichier add_livre\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
