.TH "/home/nightwalker/Class/C_Adv/biblio/inc/add_emprunt.h" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nightwalker/Class/C_Adv/biblio/inc/add_emprunt.h \- Les prototypes des fonctions qui gèrent l'ajout d'un nouvel Emprunt\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'sqlite3_client\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBadd_emprunt\fP (void)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Les prototypes des fonctions qui gèrent l'ajout d'un nouvel Emprunt\&. 


.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuteur\fP
.RS 4
\fCKOUASSI Yao Kan\fP 
.RE
.PP
\fBDate\fP
.RS 4
25 Avril 2021 
.RE
.PP

.PP
Définition dans le fichier \fBadd_emprunt\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void add_emprunt (void)"

.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void
.RE
.PP
Enregistre un nouvel Emprunt dans la base de donnees\&. Les informations de l'Emprunt sont demandees de façon interactive 
.PP
Définition à la ligne 22 du fichier add_emprunt\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
