.TH "/home/nightwalker/Class/C_Adv/biblio/inc/back_emprunt.h" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nightwalker/Class/C_Adv/biblio/inc/back_emprunt.h \- Les prototypes des fonctions qui gèrent le retour d'un Livre\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'sqlite3_client\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBback_emprunt\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Les prototypes des fonctions qui gèrent le retour d'un Livre\&. 


.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuteur\fP
.RS 4
\fCKOUASSI Yao Kan\fP 
.RE
.PP
\fBDate\fP
.RS 4
25 Avril 2021 
.RE
.PP

.PP
Définition dans le fichier \fBback_emprunt\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void back_emprunt ()"

.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void
.RE
.PP
Enregistre le retour du Livre en base de donnees 
.PP
Définition à la ligne 22 du fichier back_emprunt\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
