.TH "/home/nightwalker/Class/C_Adv/biblio/inc/delete_adherent.h" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nightwalker/Class/C_Adv/biblio/inc/delete_adherent.h \- Les prototypes des fonctions qui suppriment des Adherent de la base de donnees\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'sqlite3_client\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBdelete_adherent\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Les prototypes des fonctions qui suppriment des Adherent de la base de donnees\&. 


.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuteur\fP
.RS 4
\fCKOUASSI Yao Kan\fP 
.RE
.PP
\fBDate\fP
.RS 4
25 Avril 2021 
.RE
.PP

.PP
Définition dans le fichier \fBdelete_adherent\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void delete_adherent ()"

.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void
.RE
.PP
Supprime des adherents de la base de donnees suivant les informations des adherents fournies interactivement 
.PP
Définition à la ligne 23 du fichier delete_adherent\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
