.TH "f_cell" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_cell
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBf_string_buffer_t\fP * \fBstr_buffer\fP"
.br
.ti -1c
.RI "enum f_cell_type \fBcell_type\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 2297 du fichier fort\&.c\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
