.TH "f_cell_props" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_cell_props
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "size_t \fBcell_row\fP"
.br
.ti -1c
.RI "size_t \fBcell_col\fP"
.br
.ti -1c
.RI "uint32_t \fBproperties_flags\fP"
.br
.ti -1c
.RI "unsigned int \fBcol_min_width\fP"
.br
.ti -1c
.RI "enum \fBft_text_alignment\fP \fBalign\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_padding_top\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_padding_bottom\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_padding_left\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_padding_right\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_empty_string_height\fP"
.br
.ti -1c
.RI "enum \fBft_row_type\fP \fBrow_type\fP"
.br
.ti -1c
.RI "unsigned int \fBcontent_fg_color_number\fP"
.br
.ti -1c
.RI "unsigned int \fBcontent_bg_color_number\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_bg_color_number\fP"
.br
.ti -1c
.RI "enum \fBft_text_style\fP \fBcell_text_style\fP"
.br
.ti -1c
.RI "enum \fBft_text_style\fP \fBcontent_text_style\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1889 du fichier fort\&.c\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
