.TH "f_conv_context" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_conv_context
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBbuf\fP"
.br
.ti -1c
.RI "   wchar_t * \fBwbuf\fP"
.br
.ti -1c
.RI "   const void * \fBu8str\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "size_t \fBraw_avail\fP"
.br
.ti -1c
.RI "struct \fBf_context\fP * \fBcntx\fP"
.br
.ti -1c
.RI "enum f_string_type \fBb_type\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 181 du fichier fort\&.c\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
