.TH "fort_border_style" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort_border_style
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "const char * \fBborder_chars\fP [BORDER_ITEM_POS_SIZE]"
.br
.ti -1c
.RI "const char * \fBheader_border_chars\fP [BORDER_ITEM_POS_SIZE]"
.br
.ti -1c
.RI "const char * \fBseparator_chars\fP [SEPARATOR_ITEM_POS_SIZE]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 2011 du fichier fort\&.c\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
