.TH "ft_border_chars" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_border_chars
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "const char * \fBtop_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBseparator_ch\fP"
.br
.ti -1c
.RI "const char * \fBbottom_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBside_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBout_intersect_ch\fP"
.br
.ti -1c
.RI "const char * \fBin_intersect_ch\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure describing border appearance\&. 
.PP
Définition à la ligne 688 du fichier fort\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
