.TH "ft_table" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_table
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBf_vector_t\fP * \fBrows\fP"
.br
.ti -1c
.RI "\fBf_table_properties_t\fP * \fBproperties\fP"
.br
.ti -1c
.RI "\fBf_string_buffer_t\fP * \fBconv_buffer\fP"
.br
.ti -1c
.RI "size_t \fBcur_row\fP"
.br
.ti -1c
.RI "size_t \fBcur_col\fP"
.br
.ti -1c
.RI "\fBf_vector_t\fP * \fBseparators\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 2231 du fichier fort\&.c\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
