.TH "/home/nightwalker/Class/C_Adv/biblio/inc/list_livres.h" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nightwalker/Class/C_Adv/biblio/inc/list_livres.h \- Les prototypes des fonctions qui affichent la liste des Livres\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'sqlite3_client\&.h'\fP
.br
\fC#include 'fort\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBlist_livres\fP (void)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Les prototypes des fonctions qui affichent la liste des Livres\&. 


.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuteur\fP
.RS 4
\fCKOUASSI Yao Kan\fP 
.RE
.PP
\fBDate\fP
.RS 4
25 Avril 2021 
.RE
.PP

.PP
Définition dans le fichier \fBlist_livres\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void list_livres (void)"

.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void
.RE
.PP
Affiche la liste des Livres de la base de donnees 
.PP
Définition à la ligne 37 du fichier list_livres\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
