.TH "/home/nightwalker/Class/C_Adv/biblio/inc/seed.h" 3 "Mardi 27 Avril 2021" "Version 1.0.0" "La Mini-Biblio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nightwalker/Class/C_Adv/biblio/inc/seed.h \- Enregistrement des Livres et des Adherents aleatoires\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'sqlite3_client\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBseed\fP (void)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Enregistrement des Livres et des Adherents aleatoires\&. 


.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuteur\fP
.RS 4
\fCKOUASSI Yao Kan\fP 
.RE
.PP
\fBDate\fP
.RS 4
25 Avril 2021 
.RE
.PP

.PP
Définition dans le fichier \fBseed\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "void seed (void)"
Enregistre des Livres et des Adherents predefinis, pour des raisons de test
.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.PP
Définition à la ligne 15 du fichier seed\&.c\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour La Mini-Biblio à partir du code source\&.
