sqlite3_client.c
_SQLITE3_CLIENT_
const char* DB_FILE
Le chemin vers le fichier de base de donnees
Referenced by add_adherent, add_emprunt, add_livre, back_emprunt, connect, delete_adherent, delete_livre, find_adherent, find_livre, list_adherents, list_emprunts, list_livres, seed.
void clear_buffer()
Nettoie le tampon apres un appel scanf void void
Referenced by add_adherent, add_emprunt, add_livre, back_emprunt, find_adherent, find_livre.
char* trim(char *str)
sqlite3* connect()
void sqlite3* une instance de connexion SQLite3 Teste la connectivite avec la base de donnees et affiche une alerte sur l'etat
References DB_FILE.